server: 
  port : 8080

spring:
  application:
    name: oauth2-server
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/hdgj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000 
      connection-test-query: SELECT 1
        
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/hdgj?replSet=rs0,mongodb://127.0.0.1:27018/hdgj

management:
  endpoints:
    web:
      exposure:
        include:
          beans

security:
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

mybatis-plus: 
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   ##显示SQL语句日志

    
weidian: 
  appkey: 690844
  secret: 70fcc365ada025c1a0771545e089d118 
  
wx: 
  appid: wx14dab1d46206aee9   
  secret: 8c4630c8e4bf605ea6825c215e454634
  grant_type: authorization_code
  
jobs: 
  initialDelay: 1000      #开始1秒后
  fixedRate: 300000    #每5分钟执行一次
  
  

  
